### ISSUE TITLE
When newline follows text, textbox doesn't reposition to next line

### ISSUE THREAD

**Issue by francisluong** [craigy/type-focus#2]
To Reproduce

```
a b c<ENTER>1 2 3
````

**Comment by SkippyLives** [comment]
oh i see ya if you don't end with a sentence punctuation so it is still on the word. you can do space to get it off the word then hit enter but ya if you are in a word and hit enter it ends the word but doen't move down until after you finish the next word.

**Comment by francisluong** [comment]
MinnesoOUta
